import type { Metadata } from "next";
import { Geist, Geist_Mono, Julius_Sans_One, Lexend } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const juliusSans = Julius_Sans_One({
  weight: "400",
  variable: "--font-julius-sans",
  subsets: ["latin"],
});

const lexendSans = Lexend({
  variable: "--font-lexend-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Arsene",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${juliusSans.variable} ${lexendSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
